stages:
- check
- test
- build
- release

variables:
  GO_VERSION: "1.12.9"
  KUBERMATIC_EDITION: ce

before_script:
- mkdir -p /go/src/github.com/kubermatic/
- cp -r $PWD /go/src/github.com/kubermatic/kubermatic
- cd /go/src/github.com/kubermatic/kubermatic

dep:
  stage: check
  image:
    name: metalmatze/dep:0.5.0
    entrypoint: ['']
  script:
  - cd api
  - dep ensure -v
  - '[[ -z "$(git diff)" ]]'

gofmt:
  stage: check
  image: golang:${GO_VERSION}
  script:
  - cd api
  - make gofmt

lint-docker:
  stage: check

  image: hadolint/hadolint:latest-debian

  script:
    - hadolint api/Dockerfile

verify-codegen:
  stage: check
  image: golang:${GO_VERSION}
  script:
  - apt-get update && apt-get install -y --no-install-recommends bzr
  - cd api
  - ./hack/verify-codegen.sh

#verify-api-client:
#  stage: check
#  image: golang:${GO_VERSION}
#  script:
#    - cd api
#    - GO111MODULE=on ./hack/verify-api-client.sh

license-validation:
  stage: check
  image: metalmatze/wwhrd:1.9
  script:
  - cd api
  - wwhrd check -f ../allowed_licensed.yaml

lint:
  stage: check
  image: golangci/golangci-lint:v1.30.0
  script:
  - cd api
  - export KUBERMATIC_EDITION=ee
  - make lint
  variables:
    GOLANGCI_LINT_CACHE: ${CI_PROJECT_DIR}/api/vendor/linter-cache
    GOCACHE: ${CI_PROJECT_DIR}/api/vendor/cache
  cache:
    key: lintercache
    paths:
      - api/vendor/linter-cache
      - api/vendor/cache

verify-swagger-spec:
  stage: check
  image: golang:${GO_VERSION}
  script:
  - cd api
  - ./hack/verify-swagger.sh

test-go:
  stage: test
  image: golang:${GO_VERSION}
  script:
  - cd api
  - CGO_ENABLED=1 go test -tags "unit ${KUBERMATIC_EDITION}" -race ./...
  variables:
    GOCACHE: ${CI_PROJECT_DIR}/api/vendor/cache
  cache:
    key: test-go-cache
    paths:
      - api/vendor/cache

test-cloud:
  stage: test
  image: golang:${GO_VERSION}
  script:
  - cd api
  - go test -tags "cloud ${KUBERMATIC_EDITION}" -run nope ./pkg/test/e2e/api/...
  variables:
    GOCACHE: ${CI_PROJECT_DIR}/api/vendor/cache
  cache:
    key: test-cloud-cache
    paths:
      - api/vendor/cache

test-create:
  stage: test
  image: golang:${GO_VERSION}
  script:
  - cd api
  - go test -tags "create ${KUBERMATIC_EDITION}" -run nope ./pkg/test/e2e/api/...
  variables:
    GOCACHE: ${CI_PROJECT_DIR}/api/vendor/cache
  cache:
    key: test-create-cache
    paths:
      - api/vendor/cache

test-e2e:
  stage: test
  image: golang:${GO_VERSION}
  script:
  - cd api
  - go test -tags "e2e ${KUBERMATIC_EDITION}" -run nope ./pkg/test/e2e/api/...
  variables:
    GOCACHE: ${CI_PROJECT_DIR}/api/vendor/cache
  cache:
    key: test-e2e-cache
    paths:
      - api/vendor/cache

test-integration:
  stage: test
  image: golang:${GO_VERSION}
  script:
  - cd api
  - go test -tags "integration ${KUBERMATIC_EDITION}" -run nope ./...
  variables:
    GOCACHE: ${CI_PROJECT_DIR}/api/vendor/cache
  cache:
    key: test-integration-cache
    paths:
      - api/vendor/cache

build-kubermatic:
  stage: build
  image: golang:${GO_VERSION}
  script:
  - cd api
  - export KUBERMATIC_EDITION=ee
  - KUBERMATICCOMMIT=$CI_COMMIT_TAG make build
  - cp -r _build ${CI_PROJECT_DIR}/api/_build
  artifacts:
    paths:
    - api/_build
  variables:
    GOCACHE: ${CI_PROJECT_DIR}/api/vendor/cache
  cache:
    key: build-kubermatic
    paths:
      - api/vendor/cache

build-dnatcontroller:
  stage: build
  image: golang:${GO_VERSION}
  script:
    - cd api/cmd/kubeletdnat-controller
    - export KUBERMATIC_EDITION=ee
    - make build
    - cp -r _build ${CI_PROJECT_DIR}/api/cmd/kubeletdnat-controller/_build
  artifacts:
    paths:
      - api/cmd/kubeletdnat-controller/_build

docker-release-kubermatic:
  stage: release
  image: docker:latest
  script:
  - cd api
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker login -u sys11kubermatic -p $DOCKER_PASSWORD
  - docker build --tag syseleven/kubermatic:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:latest .
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  - docker push $CI_REGISTRY_IMAGE:latest
  - docker push syseleven/kubermatic:$CI_COMMIT_TAG
  dependencies:
  - build-kubermatic
  only:
  - tags

docker-release-dnatcontroller:
  stage: release
  image: docker:latest
  script:
    - cd api/cmd/kubeletdnat-controller
    - docker login -u sys11kubermatic -p $DOCKER_PASSWORD
    - docker build --tag syseleven/kubeletdnat-controller:$CI_COMMIT_TAG .
    - docker push syseleven/kubeletdnat-controller:$CI_COMMIT_TAG
  dependencies:
    - build-dnatcontroller
  only:
    - tags
