// Code generated by client-gen. DO NOT EDIT.

package v1

type AddonExpansion interface{}

type AddonConfigExpansion interface{}

type ClusterExpansion interface{}

type KubermaticSettingExpansion interface{}

type MachineDeploymentRequestExpansion interface{}

type ProjectExpansion interface{}

type UserExpansion interface{}

type UserProjectBindingExpansion interface{}

type UserSSHKeyExpansion interface{}
