// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	scheme "github.com/kubermatic/kubermatic/api/pkg/crd/client/clientset/versioned/scheme"
	v1 "github.com/kubermatic/kubermatic/api/pkg/crd/kubermatic/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MachineDeploymentRequestsGetter has a method to return a MachineDeploymentRequestInterface.
// A group's client should implement this interface.
type MachineDeploymentRequestsGetter interface {
	MachineDeploymentRequests(namespace string) MachineDeploymentRequestInterface
}

// MachineDeploymentRequestInterface has methods to work with MachineDeploymentRequest resources.
type MachineDeploymentRequestInterface interface {
	Create(*v1.MachineDeploymentRequest) (*v1.MachineDeploymentRequest, error)
	Update(*v1.MachineDeploymentRequest) (*v1.MachineDeploymentRequest, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.MachineDeploymentRequest, error)
	List(opts metav1.ListOptions) (*v1.MachineDeploymentRequestList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MachineDeploymentRequest, err error)
	MachineDeploymentRequestExpansion
}

// machineDeploymentRequests implements MachineDeploymentRequestInterface
type machineDeploymentRequests struct {
	client rest.Interface
	ns     string
}

// newMachineDeploymentRequests returns a MachineDeploymentRequests
func newMachineDeploymentRequests(c *KubermaticV1Client, namespace string) *machineDeploymentRequests {
	return &machineDeploymentRequests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the machineDeploymentRequest, and returns the corresponding machineDeploymentRequest object, and an error if there is any.
func (c *machineDeploymentRequests) Get(name string, options metav1.GetOptions) (result *v1.MachineDeploymentRequest, err error) {
	result = &v1.MachineDeploymentRequest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinedeploymentrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MachineDeploymentRequests that match those selectors.
func (c *machineDeploymentRequests) List(opts metav1.ListOptions) (result *v1.MachineDeploymentRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.MachineDeploymentRequestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinedeploymentrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested machineDeploymentRequests.
func (c *machineDeploymentRequests) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("machinedeploymentrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a machineDeploymentRequest and creates it.  Returns the server's representation of the machineDeploymentRequest, and an error, if there is any.
func (c *machineDeploymentRequests) Create(machineDeploymentRequest *v1.MachineDeploymentRequest) (result *v1.MachineDeploymentRequest, err error) {
	result = &v1.MachineDeploymentRequest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("machinedeploymentrequests").
		Body(machineDeploymentRequest).
		Do().
		Into(result)
	return
}

// Update takes the representation of a machineDeploymentRequest and updates it. Returns the server's representation of the machineDeploymentRequest, and an error, if there is any.
func (c *machineDeploymentRequests) Update(machineDeploymentRequest *v1.MachineDeploymentRequest) (result *v1.MachineDeploymentRequest, err error) {
	result = &v1.MachineDeploymentRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machinedeploymentrequests").
		Name(machineDeploymentRequest.Name).
		Body(machineDeploymentRequest).
		Do().
		Into(result)
	return
}

// Delete takes name of the machineDeploymentRequest and deletes it. Returns an error if one occurs.
func (c *machineDeploymentRequests) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinedeploymentrequests").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *machineDeploymentRequests) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinedeploymentrequests").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched machineDeploymentRequest.
func (c *machineDeploymentRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MachineDeploymentRequest, err error) {
	result = &v1.MachineDeploymentRequest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("machinedeploymentrequests").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
