{{- range .Values.iap.deployments }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iap-{{ .name }}-configmap
data:
  config.yaml: |
{{- with .config }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .signin_page }}
    sign-in-page: /config/signin.html
  signin.html: |
{{ toYaml .signin_page | b64dec | indent 4 }}
{{- end }}
{{ end }}
