// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UnsealVaultReq unsealVaultReq defines HTTP request for unsealVaultAddon
// swagger:model unsealVaultReq
type UnsealVaultReq struct {

	// body
	Body *UnsealKeys `json:"Body,omitempty"`

	// in: path
	// Required: true
	ClusterID *string `json:"cluster_id"`

	// in: path
	// Required: true
	DC *string `json:"dc"`

	// in: path
	// Required: true
	ProjectID *string `json:"project_id"`
}

// Validate validates this unseal vault req
func (m *UnsealVaultReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClusterID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDC(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnsealVaultReq) validateBody(formats strfmt.Registry) error {

	if swag.IsZero(m.Body) { // not required
		return nil
	}

	if m.Body != nil {
		if err := m.Body.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Body")
			}
			return err
		}
	}

	return nil
}

func (m *UnsealVaultReq) validateClusterID(formats strfmt.Registry) error {

	if err := validate.Required("cluster_id", "body", m.ClusterID); err != nil {
		return err
	}

	return nil
}

func (m *UnsealVaultReq) validateDC(formats strfmt.Registry) error {

	if err := validate.Required("dc", "body", m.DC); err != nil {
		return err
	}

	return nil
}

func (m *UnsealVaultReq) validateProjectID(formats strfmt.Registry) error {

	if err := validate.Required("project_id", "body", m.ProjectID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UnsealVaultReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnsealVaultReq) UnmarshalBinary(b []byte) error {
	var res UnsealVaultReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
