{{ if (contains .Values 'keycloak') }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
data:
  KEYCLOAK_EXTERNAL_URL:  {{ .Values.keycloak.external.url | b64enc }}
  KEYCLOAK_EXTERNAL_ADMIN_USER: {{ .Values.keycloak.external.adminUser | b64enc }}
  KEYCLOAK_EXTERNAL_ADMIN_PASSWORD: {{ .Values.keycloak.external.adminPassword | b64enc }}
  KEYCLOAK_INTERNAL_URL:  {{ .Values.keycloak.internal.url | b64enc }}
  KEYCLOAK_INTERNAL_ADMIN_USER:  {{ .Values.keycloak.internal.adminUser | b64enc }}
  KEYCLOAK_INTERNAL_ADMIN_PASSWORD: {{ .Values.keycloak.internal.adminPassword | b64enc }}
{{ end }}
