// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kubermaticv1 "github.com/kubermatic/kubermatic/api/pkg/crd/kubermatic/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMachineDeploymentRequests implements MachineDeploymentRequestInterface
type FakeMachineDeploymentRequests struct {
	Fake *FakeKubermaticV1
	ns   string
}

var machinedeploymentrequestsResource = schema.GroupVersionResource{Group: "kubermatic.k8s.io", Version: "v1", Resource: "machinedeploymentrequests"}

var machinedeploymentrequestsKind = schema.GroupVersionKind{Group: "kubermatic.k8s.io", Version: "v1", Kind: "MachineDeploymentRequest"}

// Get takes name of the machineDeploymentRequest, and returns the corresponding machineDeploymentRequest object, and an error if there is any.
func (c *FakeMachineDeploymentRequests) Get(name string, options v1.GetOptions) (result *kubermaticv1.MachineDeploymentRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(machinedeploymentrequestsResource, c.ns, name), &kubermaticv1.MachineDeploymentRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubermaticv1.MachineDeploymentRequest), err
}

// List takes label and field selectors, and returns the list of MachineDeploymentRequests that match those selectors.
func (c *FakeMachineDeploymentRequests) List(opts v1.ListOptions) (result *kubermaticv1.MachineDeploymentRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(machinedeploymentrequestsResource, machinedeploymentrequestsKind, c.ns, opts), &kubermaticv1.MachineDeploymentRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kubermaticv1.MachineDeploymentRequestList{ListMeta: obj.(*kubermaticv1.MachineDeploymentRequestList).ListMeta}
	for _, item := range obj.(*kubermaticv1.MachineDeploymentRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested machineDeploymentRequests.
func (c *FakeMachineDeploymentRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(machinedeploymentrequestsResource, c.ns, opts))

}

// Create takes the representation of a machineDeploymentRequest and creates it.  Returns the server's representation of the machineDeploymentRequest, and an error, if there is any.
func (c *FakeMachineDeploymentRequests) Create(machineDeploymentRequest *kubermaticv1.MachineDeploymentRequest) (result *kubermaticv1.MachineDeploymentRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(machinedeploymentrequestsResource, c.ns, machineDeploymentRequest), &kubermaticv1.MachineDeploymentRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubermaticv1.MachineDeploymentRequest), err
}

// Update takes the representation of a machineDeploymentRequest and updates it. Returns the server's representation of the machineDeploymentRequest, and an error, if there is any.
func (c *FakeMachineDeploymentRequests) Update(machineDeploymentRequest *kubermaticv1.MachineDeploymentRequest) (result *kubermaticv1.MachineDeploymentRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(machinedeploymentrequestsResource, c.ns, machineDeploymentRequest), &kubermaticv1.MachineDeploymentRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubermaticv1.MachineDeploymentRequest), err
}

// Delete takes name of the machineDeploymentRequest and deletes it. Returns an error if one occurs.
func (c *FakeMachineDeploymentRequests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(machinedeploymentrequestsResource, c.ns, name), &kubermaticv1.MachineDeploymentRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineDeploymentRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(machinedeploymentrequestsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &kubermaticv1.MachineDeploymentRequestList{})
	return err
}

// Patch applies the patch and returns the patched machineDeploymentRequest.
func (c *FakeMachineDeploymentRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *kubermaticv1.MachineDeploymentRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(machinedeploymentrequestsResource, c.ns, name, pt, data, subresources...), &kubermaticv1.MachineDeploymentRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubermaticv1.MachineDeploymentRequest), err
}
