// Code generated by lister-gen. DO NOT EDIT.

package v1

// AddonListerExpansion allows custom methods to be added to
// AddonLister.
type AddonListerExpansion interface{}

// AddonNamespaceListerExpansion allows custom methods to be added to
// AddonNamespaceLister.
type AddonNamespaceListerExpansion interface{}

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// MachineDeploymentRequestListerExpansion allows custom methods to be added to
// MachineDeploymentRequestLister.
type MachineDeploymentRequestListerExpansion interface{}

// MachineDeploymentRequestNamespaceListerExpansion allows custom methods to be added to
// MachineDeploymentRequestNamespaceLister.
type MachineDeploymentRequestNamespaceListerExpansion interface{}

// ProjectListerExpansion allows custom methods to be added to
// ProjectLister.
type ProjectListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}

// UserProjectBindingListerExpansion allows custom methods to be added to
// UserProjectBindingLister.
type UserProjectBindingListerExpansion interface{}

// UserSSHKeyListerExpansion allows custom methods to be added to
// UserSSHKeyLister.
type UserSSHKeyListerExpansion interface{}
