// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kubermatic/kubermatic/api/pkg/crd/kubermatic/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MachineDeploymentRequestLister helps list MachineDeploymentRequests.
type MachineDeploymentRequestLister interface {
	// List lists all MachineDeploymentRequests in the indexer.
	List(selector labels.Selector) (ret []*v1.MachineDeploymentRequest, err error)
	// MachineDeploymentRequests returns an object that can list and get MachineDeploymentRequests.
	MachineDeploymentRequests(namespace string) MachineDeploymentRequestNamespaceLister
	MachineDeploymentRequestListerExpansion
}

// machineDeploymentRequestLister implements the MachineDeploymentRequestLister interface.
type machineDeploymentRequestLister struct {
	indexer cache.Indexer
}

// NewMachineDeploymentRequestLister returns a new MachineDeploymentRequestLister.
func NewMachineDeploymentRequestLister(indexer cache.Indexer) MachineDeploymentRequestLister {
	return &machineDeploymentRequestLister{indexer: indexer}
}

// List lists all MachineDeploymentRequests in the indexer.
func (s *machineDeploymentRequestLister) List(selector labels.Selector) (ret []*v1.MachineDeploymentRequest, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.MachineDeploymentRequest))
	})
	return ret, err
}

// MachineDeploymentRequests returns an object that can list and get MachineDeploymentRequests.
func (s *machineDeploymentRequestLister) MachineDeploymentRequests(namespace string) MachineDeploymentRequestNamespaceLister {
	return machineDeploymentRequestNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MachineDeploymentRequestNamespaceLister helps list and get MachineDeploymentRequests.
type MachineDeploymentRequestNamespaceLister interface {
	// List lists all MachineDeploymentRequests in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.MachineDeploymentRequest, err error)
	// Get retrieves the MachineDeploymentRequest from the indexer for a given namespace and name.
	Get(name string) (*v1.MachineDeploymentRequest, error)
	MachineDeploymentRequestNamespaceListerExpansion
}

// machineDeploymentRequestNamespaceLister implements the MachineDeploymentRequestNamespaceLister
// interface.
type machineDeploymentRequestNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MachineDeploymentRequests in the indexer for a given namespace.
func (s machineDeploymentRequestNamespaceLister) List(selector labels.Selector) (ret []*v1.MachineDeploymentRequest, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.MachineDeploymentRequest))
	})
	return ret, err
}

// Get retrieves the MachineDeploymentRequest from the indexer for a given namespace and name.
func (s machineDeploymentRequestNamespaceLister) Get(name string) (*v1.MachineDeploymentRequest, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("machinedeploymentrequest"), name)
	}
	return obj.(*v1.MachineDeploymentRequest), nil
}
